[project]
name = "llama-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.4.2",
    "tinygrad>=0.11.0",
]
